FROM python:3.9.1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
CMD ["python","manage.py","runserver","0.0.0.0:8000"]